### ISSUE TITLE
Why require PHP 7.2?

### ISSUE THREAD

**Issue by Sainan** [mlocati/spf-lib#19]
PHP 7.2 did not add that much functionality, so I was curious if this package actually needed it, so I installed PHP 7.1 (using your amazing powershell module), replaced the `require-dev` version constraints with `"*"`, ran `composer update`, and the PHPUnit tests all ran fine:

![image](https://user-images.githubusercontent.com/63328889/106990082-d6592b00-6773-11eb-9b6b-075e3d2f9a93.png)

**Comment by mlocati** [comment]
I'm not sure we can safely use this library on PHP 7.1: we should include code coverage in tests to be sure that tests touch as many PHP files as possible

**Comment by mlocati** [comment]
> I'm not sure we can safely use this library on PHP 7.1: we should include code coverage in tests to be sure that tests touch as many PHP files as possible

Whoops... it's already implemented in this project (I guess I'm maintaining too many open source projects :wink:)
