### ISSUE TITLE
Can I supply the starting SPF record?

### ISSUE THREAD

**Issue by gunsuka** [mlocati/spf-lib#24]
Is there any way to use this library by supplying the IP, and SPF record to see if it is a valid IP according to the SPF record I provide?

Currently you can supply the IP & domain name and it will lookup the TXT record in DNS.

I would like to supply my own starting TXT record and an associated IP address.  Then the system could perform its checks.  Possible?

**Comment by mlocati** [comment]
Sure: you can use the `SPFLib\Check\Environment` class to do that.

**Comment by mlocati** [comment]
You can also use a custom `SPFLib\DNS\Resolver` class to emulate a TXT record for specific domains.

**Comment by gunsuka** [comment]
> 

That is fantastic that the library can already do it.   Is there any documentation or example?  I looked through the code but I can't see anything that looks like I would be able to push an IP address and SPF record into the system.

**Comment by mlocati** [comment]
No documentation.
You can use the `SPFLib\Checker` class.
- When building an instance of it, use a custom `SPFLib\DNS\Resolver` instance that provides the TXT records for your domiains.
- When invoking its `check` method, use an `SPFLib\Check\Environment` containing the IP address you want.
