### ISSUE TITLE
Translation ?

### ISSUE THREAD

**Issue by Erwane** [mlocati/spf-lib#26]
hi,
Do you think it's possible to extract all issues descriptions with variables in a standard format (like `sprintf()`)  to allow translation ?
Thanks

**Comment by mlocati** [comment]
Since we have an exception class for almost any ptoblem, and since those exceptions come eith the relevant data, it should be rather easy to implement translation

**Comment by Erwane** [comment]
So, we should check source code to understand exceptions and messages, try to don't forget one and then rewrite them in our app with translations, even for english.
