### ISSUE TITLE
Are there any problems with ip6 records?

### ISSUE THREAD

**Issue by ITC-KEDA** [mlocati/spf-lib#31]
My code:
$decoder = new \SPFLib\Decoder();
try {
              $record = $decoder->getRecordFromDomain($input);
} catch (\SPFLib\Exception $x) {
              $text ="There are problems with getting the SPF, or it can't be decoded";
}

print_r($record->getMechanisms());

My php script just stop, whengetting to: print_r($record->getMechanisms());, when there are ip6 record in the spf.

**Comment by ITC-KEDA** [comment]
Sorry, no thats working. Just tested it with another. SPF. And that works fine.
So must be something else.

**Comment by ITC-KEDA** [comment]
I found root issues, i have this SPF: (IP address have been removed)
v=spf1 ip4:x.x.x.x ip4:x.x.x.x ip6: xxxx:xxxx:xxxx::/48 include:u123456.wl.sendgrid.net ~all

The problems where that there where are space between ip6 and the ipv6 address.
Therefor i got this in my log:
HP Fatal error:  Uncaught SPFLib\\Exception\\InvalidTermException: The SPF record contains an unrecognized term: ip6: in /var/www/clients/client11/web90/web/vendor/mlocati/spf-lib/src/Decoder.php:173


Could it be posible to get a error on these kind of error, instead of a php fatal error?

**Comment by mlocati** [comment]
> Could it be posible to get a error on these kind of error, instead of a php fatal error?

You can simply catch the exception:

```php
try {
   /// place your code here
} catch (\SPFLib\Exception\InvalidTermException $x) {
   // do whatever you want with the error described by $x
}
```
